---
title: "Dashboard"
author: "Steven Lawrence"
date: "4/8/2020"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(tigris) 
library(leaflet)
```

```{r, include=FALSE}
# Data

`%notin%` = Negate(`%in%`)

familytype <- read_csv("./data/FamilyType_relatedChildren_2010/DECENNIALSF12010.P39_data_with_overlays_2020-04-07T201031.csv") %>% 
  filter(GEO_ID %notin% "id") %>% 
  separate(NAME, c("GZ","zcta", "city"), sep = " ") %>% 
  separate(zcta, c("zcta"), sep = ",") %>% 
  dplyr::select(-GZ, -city)

household <- read_csv("./data/HouseholdSize_HousingTenure_2010/DECENNIALSF12010.H12_data_with_overlays_2020-04-07T190301.csv") %>% 
  filter(GEO_ID %notin% "id") %>% 
  separate(NAME, c("GZ","zcta", "city"), sep = " ") %>% 
  separate(zcta, c("zcta"), sep = ",") %>% 
  dplyr::select(-GZ, -city)

pophouse<- read_csv("./data/Population_by_Housing_Tenure_2010/DECENNIALSF12010.H11_data_with_overlays_2020-04-07T184308.csv") %>% 
  filter(GEO_ID %notin% "id") %>% 
  separate(NAME, c("GZ","zcta", "city"), sep = " ") %>% 
  separate(zcta, c("zcta"), sep = ",") %>% 
  dplyr::select(-GZ, -city)

ethnicity <- read_csv("./data/Race_HispanicEthnicity_2010/DECENNIALSF12010.P11_data_with_overlays_2020-04-07T194537.csv") %>% 
  filter(GEO_ID %notin% "id") %>% 
  separate(NAME, c("GZ","zcta", "city"), sep = " ") %>% 
  separate(zcta, c("zcta"), sep = ",") %>% 
  dplyr::select(-GZ, -city)

sexAge <- read_csv("./data/Sex_by_Age_2010/DECENNIALSF12010.P12_data_with_overlays_2020-04-07T195143.csv") %>% 
  filter(GEO_ID %notin% "id") %>% 
  separate(NAME, c("GZ","zcta", "city"), sep = " ") %>% 
  separate(zcta, c("zcta"), sep = ",") %>% 
  dplyr::select(-GZ, -city)

covid_data = read.csv("https://raw.githubusercontent.com/nychealth/coronavirus-data/master/tests-by-zcta.csv") %>% 
 na.omit() %>% 
 as_tibble() %>% 
janitor::clean_names() %>% 
  mutate(zcta = factor(modzcta))


covid<- Reduce(function(x,y) left_join(x = x, y = y, by = "zcta"),
       list(familytype, household, pophouse, ethnicity, sexAge, covid_data )) %>% 
       # dplyr::select(-GEO_ID.y,-GEO_ID.x) %>% 
        mutate(
          H012001 = as.numeric(H012001),
         H011001 = as.numeric(H011001),
           P011005 = as.numeric(P011005),
          P012020 =as.numeric(P012020),
          P012021 = as.numeric(P012021) ,
         P012022 = as.numeric(P012022) ,
        P012023 = as.numeric(P012023),
         P012024 = as.numeric(P012024) ,
       P012025 = as.numeric(P012025) ,
        P012044  = as.numeric(P012044) ,
         P012045  = as.numeric(P012045),
        P012046  = as.numeric(P012046) ,
        P012047  = as.numeric(P012047) ,
        P012048  = as.numeric(P012048) ,
          P012049  = as.numeric(P012049),
       P012001 = as.numeric(P012001),
       P011001 = as.numeric(P011001)
       ) %>% 
          
        rename(
          "house_hold_total" = H012001,
         "Pop_inhouse_total"= H011001 ,
          "POP_white_alone"= P011005 ,
          "total_male_65-66" =P012020 ,
         "total_male_67-69" = P012021 ,
          "total_male_70-74" = P012022  ,
         "total_male_75-79" = P012023 ,
         "total_Male_80-84" = P012024  ,
          "total_male_85+" = P012025  ,
          "total_female_65-66" = P012044 ,
         "total_female_67-69" = P012045 ,
         "total_female_70-74" = P012046  ,
         "total_female_75-79" = P012047 ,
         "total_female_80-84" = P012048 ,
           "total_female_85+" = P012049,
         "total_pop" = P012001,
         "total_race_pop" = P011001
        ) %>% 
  mutate(aga65_above =
          `total_male_65-66` +
         `total_male_67-69`+
          `total_male_70-74`+
         `total_male_75-79`+
         `total_Male_80-84`+
          `total_male_85+` +
          `total_female_65-66`+
         `total_female_67-69` +
         `total_female_70-74`+
         `total_female_75-79`+
         `total_female_80-84`+
           `total_female_85+`) %>% 
  #dropping longisland 06390
  filter(zcta %notin% "06390") %>% 
  mutate(
    case_rate_pop = positive/total_pop*100000,
    case_rate_ht = positive/`house_hold_total`,
         case_rate_popinht = positive/`Pop_inhouse_total`,
          case_rate_nonW = positive*100000/(total_race_pop -POP_white_alone),
         case_rate_ageAbove_65 = positive*100000/aga65_above)

```

```{r, include=F}
#nys shape file
nycshape4 <- zctas(cb = T, starts_with = c("100","101","102 ","103","104","107","110","112","113", "114", "116"))

```

```{r, include=F}

#joining file with population data
zipsmap <- geo_join(nycshape4, 
                      covid, 
                      by_sp = "GEOID10", 
                      by_df = "zcta",
                      how = "left")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
pal <- colorNumeric(
  palette = "Blues",
  domain = zipsmap@data$case_rate_pop)
# create labels for zipcodes
labels <- 
  paste0(
    "Zip Code: ",
    zipsmap@data$GEOID10, "<br/>",
    "Total Cases: ",
   round(zipsmap@data$case_rate_pop, digits = 0)) %>%
  lapply(htmltools::HTML)

 zipsmap %>% leaflet %>% 
  # add base map
  addProviderTiles("CartoDB") %>% 
  # add zip codes
  addPolygons(fillColor = ~pal(case_rate_pop),
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "3",
              fillOpacity = 0.7,
              highlight = highlightOptions(weight = 2,
                                           color = "#666",
                                           dashArray = "",
                                           fillOpacity = 0.7,
                                           bringToFront = TRUE),
              label = labels) %>%
  # add legend
  addLegend(pal = pal, 
            values = ~case_rate_pop, 
            opacity = 0.7, 
            title = htmltools::HTML("Case Rate <br/>per 100k"),
            position = "bottomright")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
pal <- colorNumeric(
  palette = "Oranges",
  domain = zipsmap@data$case_rate_ageAbove_65)
# create labels for zipcodes
labels <- 
  paste0(
    "Zip Code: ",
    zipsmap@data$GEOID10, "<br/>",
    "Total Cases: ",
   round(zipsmap@data$case_rate_ageAbove_65, digits = 0)) %>%
  lapply(htmltools::HTML)

 zipsmap %>% leaflet %>% 
  # add base map
  addProviderTiles("CartoDB") %>% 
  # add zip codes
  addPolygons(fillColor = ~pal(case_rate_ageAbove_65),
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "3",
              fillOpacity = 0.7,
              highlight = highlightOptions(weight = 2,
                                           color = "#666",
                                           dashArray = "",
                                           fillOpacity = 0.7,
                                           bringToFront = TRUE),
              label = labels) %>%
  # add legend
  addLegend(pal = pal, 
            values = ~case_rate_ageAbove_65, 
            opacity = 0.7, 
            title = htmltools::HTML("Case Rate <br/>Age 65 +"),
            position = "bottomright")

```

### Chart C

```{r}
pal <- colorNumeric(
  palette = "Purples",
  domain = zipsmap@data$case_rate_nonW)
# create labels for zipcodes
labels <- 
  paste0(
    "Zip Code: ",
    zipsmap@data$GEOID10, "<br/>",
    "Total Cases: ",
   round(zipsmap@data$case_rate_nonW, digits = 0)) %>%
  lapply(htmltools::HTML)

 zipsmap %>% leaflet %>% 
  # add base map
  addProviderTiles("CartoDB") %>% 
  # add zip codes
  addPolygons(fillColor = ~pal(case_rate_nonW),
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "3",
              fillOpacity = 0.7,
              highlight = highlightOptions(weight = 2,
                                           color = "#666",
                                           dashArray = "",
                                           fillOpacity = 0.7,
                                           bringToFront = TRUE),
              label = labels) %>%
  # add legend
  addLegend(pal = pal, 
            values = ~case_rate_nonW, 
            opacity = 0.7, 
            title = htmltools::HTML("Case Rate <br/>Non White"),
            position = "bottomright")
```